apiVersion: secret_scope.crossplane.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: secret_scope/v1alpha1/scope
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    name: terraform-demo-scope
