apiVersion: databricks.crossplane.io/v1alpha1
kind: ClusterPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/clusterpolicy
  labels:
    testing.upbound.io/example-name: fair_use
  name: fair-use
spec:
  forProvider:
    definition: ${jsonencode(merge(local.default_policy, var.policy_overrides))}
    libraries:
    - pypi:
      - package: databricks-sdk==0.12.0
    name: ${var.team} cluster policy
