apiVersion: databricks.crossplane.io/v1alpha1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/secretscope
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    name: terraform-demo-scope
